# Generated by Django 2.1.5 on 2020-01-09 00:57

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appBase', '0002_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='encabezado',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
